(library
 (name test_definitions)
 (modules test_definitions)
 (libraries core riscvemulate)
 (preprocess
  (pps ppx_jane)))

(library
 (name trap_test_utils)
 (modules trap_test_utils)
 (libraries core riscvemulate sim)
 (preprocess
  (pps ppx_jane)))

(tests
 (names basic fuzz_tests csr_tests trap_csr_tests trap_tests)
 (modules
  basic
  fuzz_tests
  csr_tests
  trap_csr_tests
  trap_tests)
 (libraries
  core
  hardcaml
  privileged
  riscvemulate
  sim
  fuzz
  test_definitions
  trap_test_utils)
 (preprocess
  (pps ppx_jane ppx_hardcaml ppx_sexp_conv)))
