(library
 (name test_definitions)
 (modules test_definitions)
 (libraries core riscvemulate)
 (preprocess
  (pps ppx_jane)))

(tests
 (names basic fuzz_tests csr_tests)
 (modules basic fuzz_tests csr_tests)
 (libraries core hardcaml privileged riscvemulate sim fuzz test_definitions)
 (preprocess
  (pps ppx_jane ppx_sexp_conv)))
