(library
 (name test_definitions)
 (modules test_definitions)
 (libraries core riscv_isa riscvemulate)
 (preprocess
  (pps ppx_jane)))

(library
 (name trap_test_utils)
 (modules trap_test_utils)
 (libraries core riscv_isa riscvemulate sim)
 (preprocess
  (pps ppx_jane)))

(tests
 (names basic fencei)
 (modules basic fencei)
 (libraries core hardcaml riscv_isa riscvemulate sim test_definitions)
 (preprocess
  (pps ppx_jane ppx_hardcaml ppx_sexp_conv)))
